site_name: OpenWorm Documentation
theme:
  name: material    
  favicon: images/favicon.ico
  logo: images/favicon.ico
nav:
  - Introduction : index.md
  - Background : background.md
  - History : fullhistory.md
  - Releases : releases.md
  - Modelling : modeling.md
  - Projects:
      - Projects Overview : projects.md
      - Sibernetic : Projects/sibernetic.md
      - c302 : Projects/c302.md
      - Worm Browser : Projects/browser.md
      - DevoWorm : Projects/DevoWorm.md
      - Docker simulation stack : Projects/docker.md
      - Movement : Projects/worm-movement.md
      - Geppetto : Projects/geppetto.md
      - Optimization : Projects/optimization.md
      - Representation : Projects/datarep.md
      - Community Outreach : Projects/community-proj.md
      - Muscle / Neuron /  Channel : Projects/muscle-neuron-integration.md
      - C. elegans Robots : Projects/c-elegans-robot.md
  - Community:
      - Community Overview : community.md
      - GitHub : Community/github.md
      - Repos : Community/repositories.md
      - Membership : Community/membership.md
  - Resources:
      - Resources Overview: Resources/resources.md
      - Running NeuroML connectome: Resources/running-nc.md
  - FAQ : faq.md
