site_name: OpenWorm
theme: readthedocs
nav:
  - Introduction : index.md
  - Background : background.md
  - History : fullhistory.md
  - Releases : releases.md
  - Modelling : modeling.md
  - Projects Overview : projects.md
  - Projects: 
      - Sibernetic : Projects/sibernetic.md
      - Geppetto : Projects/geppetto.md
      - Movement : Projects/worm-movement.md
      - DevoWorm : Projects/DevoWorm.md
      - Optimization : Projects/optimization.md
      - Representation : Projects/datarep.md
      - Community : Projects/community-proj.md
      - Muscle / Neuron /  Channel : Projects/muscle-neuron-integration.md
  - Community Overview : community.md
  - Community: 
      - Github : Community/github.md
      - Repos : Community/repositories.md
      - Membership : Community/membership.md
  - Resources : Resources/resources.md
  - FAQ : faq.md
