site_name: OpenWorm
theme: readthedocs
pages:
  - [index.md, Introduction]
  - [background.md, Background]
  - [fullhistory.md, History]
  - [releases.md, Releases]
  - [modeling.md, Modelling]
  - [projects.md, Projects Overview]
  - [Projects/sibernetic.md, Projects, Sibernetic]
  - [Projects/geppetto.md, Projects, Geppetto]
  - [Projects/worm-movement.md, Projects, Movement]
  - [Projects/optimization.md, Projects, Optimization]
  - [Projects/datarep.md, Projects, Representation]
  - [Projects/community-proj.md, Projects, Community]
  - [community.md, Community Overview]
  - [Community/github.md, Community, Github]
  - [Community/repositories.md, Community, Repos]
  - [Community/membership.md, Community, Membership]
  - [Resources/resources.md, Resources]
  - [faq.md, FAQ]
